CREATE TABLE UserLocations (
    id INT UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    lat DECIMAL(16,14),
    lon DECIMAL(16,14),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)