CREATE Table Users (
    id INT UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(255) UNIQUE NOT NULL,
    adventure_status TINYINT(1),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)